---
title: Phylo location-scale plot trials
author: Szymon Drobniak
date: '`r Sys.Date()`'
format:
    gfm: default
crossref:
    fig-title: Figure
    tbl-title: Table
    title-delim: —
    fig-prefix: Fig.
    tbl-prefix: Tab.
    eq-prefix: Eq.
editor_options:
    chunk_output_type: console
execute:
    cache: false
    warning: false
---

```{r}
library(here)
library(tidyverse)
library(plot3D)
library(ggplot2)


data <- read.table(
    here("data", "Psittaciformes", "Psittaciformes_354spp.csv"),
    sep = ",", header = TRUE
)

data <- data %>%
    group_by(Phylo) %>%
    mutate(Genus = strsplit(Phylo, "_")[[1]][1]) %>%
    ungroup()

length(unique(data$Genus))

data$beak_l_resid <- residuals(lm(log(Beak.Length_Culmen) ~ log(Mass), data = data))
data$beak_w_resid <- residuals(lm(log(Beak.Width) ~ log(Mass), data = data))

plot(beak_l_resid ~ log(Mass), data = data)

plot(beak_l_resid ~ beak_w_resid, data = data)

plot(log(Beak.Length_Culmen) ~ log(Beak.Width), data = data)

ggplot(data = data, aes(
    x = log(Beak.Length_Culmen),
    y = log(Beak.Width), colour = Genus
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse() +
    guides(colour = FALSE)

ggplot(data = data, aes(
    x = beak_l_resid,
    y = beak_w_resid, colour = Genus
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse() +
    guides(colour = FALSE)


ngenera <- rev(sort(table(data$Genus)))
ngenera <- ngenera[ngenera > 8]

data <- data %>%
    group_by(Genus) %>%
    mutate(
        beak_l_v = var(beak_l_resid),
        beak_w_v = var(beak_w_resid),
        beak_v = beak_l_v + beak_w_v
    )

data1 <- data %>%
    filter(Genus %in% names(ngenera))

ggplot(data = data1, aes(
    x = beak_l_resid,
    y = beak_w_resid, colour = Genus
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse() +
    guides(colour = FALSE)


ggplot(data = data1, aes(
    x = beak_l_resid,
    y = beak_w_resid, colour = log(beak_v)
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse(aes(group = Genus)) +
    guides(colour = FALSE) +
    scale_colour_gradient(low = "#0e91b9", high = "red")
```

Other traits

```{r}
data$tars_resid <- residuals(lm(log(Tarsus.Length) ~ log(Mass), data = data))
data <- data %>%
    group_by(Genus) %>%
    mutate(
        rs_v = var(Range.Size)
    )

data1 <- data %>%
    filter(Genus %in% names(ngenera))

ggplot(data = data1, aes(
    y = log(Mass),
    x = log(Range.Size), colour = log(rs_v)
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse(aes(group = Genus)) +
    guides(colour = FALSE) +
    scale_colour_gradient(low = "#0e91b9", high = "red")
```

```{r}
data$tail_resid <- residuals(lm(log(Tail.Length) ~ log(Mass), data = data))
data <- data %>%
    group_by(Genus) %>%
    mutate(
        tail_v = var(Tail.Length)
    )

data1 <- data %>%
    filter(Genus %in% names(ngenera))

ggplot(data = data1, aes(
    y = tars_resid,
    x = tail_resid, colour = log(tail_v)
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse(aes(group = Genus)) +
    guides(colour = FALSE) +
    scale_colour_gradient(low = "#0e91b9", high = "red")
```

```{r}
data$wing_resid <- residuals(lm(log(Wing.Length) ~ log(Mass), data = data))
data <- data %>%
    group_by(Genus) %>%
    mutate(
        wing_v = var(Wing.Length)
    )

data1 <- data %>%
    filter(Genus %in% names(ngenera))

ggplot(data = data1, aes(
    y = wing_resid,
    x = log(Range.Size), colour = log(rs_v)
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse(aes(group = Genus)) +
    guides(colour = FALSE) +
    scale_colour_gradient(low = "#0e91b9", high = "red")
```

```{r}
data <- data %>%
    group_by(Genus) %>%
    mutate(
        tars_v = var(Tarsus.Length)
    )

data1 <- data %>%
    filter(Genus %in% names(ngenera))

ggplot(data = data1, aes(
    y = log(Tarsus.Length),
    x = log(Mass), colour = log(rs_v)
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse(aes(group = Genus)) +
    guides(colour = FALSE) +
    scale_colour_gradient(low = "#0e91b9", high = "red")
```

```{r}
data$sec_resid <- residuals(lm(log(Secondary1) ~ log(Mass), data = data))
data <- data %>%
    group_by(Genus) %>%
    mutate(
        sec_v = var(Secondary1)
    )

data1 <- data %>%
    filter(Genus %in% names(ngenera))

ggplot(data = data1, aes(
    y = sec_resid,
    x = wing_resid, colour = log(sec_v)
)) +
    geom_point() +
    theme_bw() +
    stat_ellipse(aes(group = Genus)) +
    guides(colour = FALSE) +
    scale_colour_gradient(low = "#0e91b9", high = "red")
```